"""Eliminate locator variables and derive a constant-degree rho polynomial.

For a pure two-monomial ConjE pencil rho*x^a + x^b, this script forms the
ideal generated by:

  - P(x) | x^n - 1, encoded as rem(x^n - 1, P) = 0;
  - exact high-vector certificate equations in degrees k..n/2-1.

It then eliminates the locator coefficients of the monic half-set divisor P
and prints the rho-only polynomial factors.  A bounded rho-only degree gives a
q-uniform bound on the number of bad ratios for that template.
"""

from __future__ import annotations

import argparse

import sympy as sp


def rho_polynomials(n: int, k: int, a: int, b: int) -> list[sp.Expr]:
    x = sp.Symbol("x")
    rho = sp.Symbol("rho")
    t = n // 2
    p = sp.symbols("p0:" + str(t))
    P = x**t + sum(p[i] * x**i for i in range(t))

    divisor_eqs = [sp.expand(c) for c in sp.Poly(sp.rem(x**n - 1, P, x), x).all_coeffs()]
    rem_a = sp.Poly(sp.rem(x**a, P, x), x)
    rem_b = sp.Poly(sp.rem(x**b, P, x), x)
    cert_eqs = [
        sp.expand(rho * rem_a.coeff_monomial(x**degree) + rem_b.coeff_monomial(x**degree))
        for degree in range(k, t)
    ]
    basis = sp.groebner(divisor_eqs + cert_eqs, *p, rho, order="lex")
    out = []
    for poly in basis.polys:
        expr = sp.factor(poly.as_expr())
        if expr != 0 and not any(expr.has(var) for var in p):
            out.append(expr)
    return out


def default_cases() -> list[tuple[int, int, int, int]]:
    return [
        (8, 2, 4, 3),
        (8, 2, 2, 6),
        (16, 4, 4, 8),
        (16, 4, 4, 10),
    ]


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--n", type=int, default=None)
    parser.add_argument("--k", type=int, default=None)
    parser.add_argument("--a", type=int, default=None)
    parser.add_argument("--b", type=int, default=None)
    parser.add_argument("--default-cases", action="store_true")
    args = parser.parse_args()

    if args.default_cases:
        cases = default_cases()
    else:
        if args.n is None or args.a is None or args.b is None:
            parser.error("pass --default-cases or provide --n --a --b")
        k = args.k if args.k is not None else args.n // 4
        cases = [(args.n, k, args.a, args.b)]

    for n, k, a, b in cases:
        print(f"ratio elimination n={n} k={k} (a,b)=({a},{b})", flush=True)
        polys = rho_polynomials(n, k, a, b)
        if not polys:
            print("  <no rho-only polynomial found>")
            continue
        for expr in polys:
            degree = sp.Poly(expr, sp.Symbol("rho")).degree()
            print(f"  degree={degree}: {expr}")


if __name__ == "__main__":
    main()
