"""Singular eliminator for the two unresolved 3-mono base cases at (8, 2).

Note 0291 resolves the self-reflective cases (2, 3, 6) and (2, 5, 6) by
finite-field numerical enumeration.  This harness emits a direct Singular
certificate for the same cert+div eliminator used by
g3_3mono_base_cases.py, aiming to turn that numerical patch into a symbolic
base-case closure.
"""
from __future__ import annotations

import argparse
import subprocess
from pathlib import Path

import sympy as sp


CASES = [(2, 3, 6), (2, 5, 6)]


def singular_poly(expr: sp.Expr) -> str:
    return str(sp.expand(expr)).replace("**", "^")


def cert_div_equations(n: int, k: int, a_pos: int, b_pos: int, c_pos: int) -> list[sp.Expr]:
    z = sp.Symbol("z")
    rho = sp.Symbol("rho")
    alpha = sp.Symbol("alpha")
    t = 2 * k
    p = sp.symbols("p0:" + str(t))
    if t == 1 and not isinstance(p, tuple):
        p = (p,)
    sigma = z**t + sum(p[i] * z**i for i in range(t))

    rem_a = sp.Poly(sp.rem(z**a_pos, sigma, z), z)
    rem_b = sp.Poly(sp.rem(z**b_pos, sigma, z), z)
    rem_c = sp.Poly(sp.rem(z**c_pos, sigma, z), z)

    eqs: list[sp.Expr] = []
    for d in range(k, t):
        eqs.append(
            sp.expand(
                rem_a.coeff_monomial(z**d)
                + rho * rem_b.coeff_monomial(z**d)
                + alpha * rem_c.coeff_monomial(z**d)
            )
        )

    rem_n = sp.Poly(sp.rem(z**n - 1, sigma, z), z)
    eqs.extend(sp.expand(c) for c in rem_n.all_coeffs())
    return [e for e in eqs if e != 0]


def emit_singular(out: Path, prime: int | None = None) -> None:
    char = "0" if prime is None else str(prime)
    lines = [
        f"// Generated by {Path(__file__).name}",
        "// 3-mono unresolved base cases at (n,k)=(8,2).",
        'option(redSB);',
        f"ring R = {char}, (p0,p1,p2,p3,alpha,rho), lp;",
        "",
    ]
    for case in CASES:
        a, b, c = case
        eqs = cert_div_equations(8, 2, a, b, c)
        lines.extend(
            [
                f'print("CASE ({a},{b},{c}) BEGIN");',
                "ideal I =",
                "  " + ",\n  ".join(singular_poly(e) for e in eqs) + ";",
                "ideal G = std(I);",
                "ideal E = eliminate(G, p0*p1*p2*p3);",
                'print("ELIMINATOR");',
                "E;",
                'print("CASE END");',
                "",
            ]
        )
    out.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", type=Path, default=Path("notes/scripts/g3_3mono_singular_timeout_82.sing"))
    parser.add_argument("--output", type=Path, default=Path("notes/scripts/g3_3mono_singular_timeout_82.output.txt"))
    parser.add_argument("--prime", type=int, default=None)
    parser.add_argument("--run", action="store_true")
    parser.add_argument("--timeout", type=int, default=300)
    args = parser.parse_args()

    emit_singular(args.out, args.prime)
    print(f"wrote {args.out}")
    if not args.run:
        return

    proc = subprocess.run(
        ["Singular", "-q", str(args.out)],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        timeout=args.timeout,
        check=False,
    )
    args.output.write_text(proc.stdout, encoding="utf-8")
    print(f"Singular exit={proc.returncode}; wrote {args.output}")


if __name__ == "__main__":
    main()
