"""g3_cyclotomic_check.py — test whether bad-α sets are cyclotomic cosets.

Conjecture D: for strict above-Johnson f, bad α set has the form
  { β + h : h ∈ T }
where T is a union of cosets of a multiplicative subgroup H ≤ F_q*.

For our two witnesses at q=97:
  count=8: bad = {21, 22, 32, 47, 54, 69, 79, 80}
  count=2: bad = {14, 59}

We test:
  count=8: bad = 2 + 19 · μ_8 (coset of order-8 subgroup, scaled & translated)
  count=2: bad = 85 + 26 · μ_2 = {85 + 26, 85 - 26} = {111-97, 59} = {14, 59}
"""
import math


def order_in_Fq(g, q):
    o = 1
    v = g
    while v != 1:
        v = (v * g) % q
        o += 1
        if o > q: return -1
    return o


def subgroup_of(g, q):
    out = [1]
    v = g
    while v != 1:
        out.append(v)
        v = (v * g) % q
    return out


def find_translated_coset_struct(bad, q):
    """Try to express bad = β + λ · (T) where T is a union of cosets of some
    multiplicative subgroup H of F_q*. Return (β, λ, H_order, T_subset_of_H_cosets) or None."""
    bad = sorted(bad)
    m = len(bad)
    best = None
    # Try every translation β
    for beta in range(q):
        translates = sorted([(b - beta) % q for b in bad])
        if 0 in translates:
            continue  # not a multiplicative coset since zero appears
        # The translates form a subset of F_q*. Check whether they form a
        # multiplicative coset, i.e. translates = λ · H for some λ and subgroup H.
        # If so, all pairwise ratios translates[i]/translates[0] lie in H.
        # H is the multiplicative subgroup generated by all such ratios.
        first = translates[0]
        first_inv = pow(first, q - 2, q)
        ratios = sorted({(t * first_inv) % q for t in translates})
        # ratios should equal H (a subgroup) iff the set of ratios is closed under mult.
        # Quick check: for each pair (a, b) ∈ ratios, a*b mod q ∈ ratios.
        is_subgroup = True
        for a in ratios:
            for b in ratios:
                if (a * b) % q not in ratios:
                    is_subgroup = False
                    break
            if not is_subgroup: break
        if is_subgroup:
            H = ratios
            lam = first
            return (beta, lam, len(H), sorted(H))
    return None


def main():
    q = 97
    print(f"=== F_{q} ===")

    # Count=8
    bad8 = [21, 22, 32, 47, 54, 69, 79, 80]
    print(f"\nCount=8 bad α: {bad8}")
    res = find_translated_coset_struct(bad8, q)
    if res:
        beta, lam, h_ord, H = res
        print(f"  ✓ Found: bad = {beta} + {lam} · μ_{h_ord}")
        print(f"  H = ⟨g⟩ where |H| = {h_ord}: H = {H}")
        # Verify
        recon = sorted([(beta + lam * h) % q for h in H])
        print(f"  Reconstructed: {recon}")
        print(f"  Match: {recon == sorted(bad8)}")
        # Identify generator
        for g in H:
            if order_in_Fq(g, q) == h_ord:
                print(f"  H is generated by {g} (order {h_ord})")
                break
    else:
        print("  ✗ No translated multiplicative coset structure")

    # Count=2
    bad2 = [14, 59]
    print(f"\nCount=2 bad α: {bad2}")
    res = find_translated_coset_struct(bad2, q)
    if res:
        beta, lam, h_ord, H = res
        print(f"  ✓ Found: bad = {beta} + {lam} · μ_{h_ord}")
        print(f"  H = {H}")
        recon = sorted([(beta + lam * h) % q for h in H])
        print(f"  Reconstructed: {recon}")
        print(f"  Match: {recon == sorted(bad2)}")
    else:
        print("  ✗ No translated multiplicative coset structure")

    # Bonus: find ALL count=1 sample structures from existing data.
    # PR #373 verify_lsym_sparse.output: q=97, K=1 leader → bad_alpha=1 (alpha=0).
    # That's a singleton — trivially a coset of trivial group. Not very informative.

    # Check: is there structure when bad=1?
    bad1 = [0]
    print(f"\nCount=1 (PR #373 K=1 leader): {bad1}")
    res = find_translated_coset_struct(bad1, q)
    if res:
        print(f"  ✓ trivial coset structure: {res}")


if __name__ == "__main__":
    main()
