"""g3_reverse_sat_alpha_structure.py — analyze the 9 saturating α_1 values in
Reverse Pattern (15, 18, 19) at (32, 8). Test:

  (a) Are they roots of a low-degree polynomial P_f(α_1)?
  (b) Is that polynomial a trinomial / Bluher-shaped?
  (c) Does the set form a coset / additive subgroup / multiplicative coset?
  (d) Do they correspond to specific (f_e)_o + α_1·(f_o)_o structures?

The goal is to pin down a CLOSED-FORM polynomial whose roots are |B_1| ≤ 9
under recursive above-J — bridging to Bluher's Hilbert-90 framework.
"""
import sys, os, random
sys.path.insert(0, os.path.expanduser('~/Desktop/2026/ef1m/notes/scripts'))

import numpy as np
from itertools import combinations
from fri_2round_attack import setup_chain, even_odd_parts, modinv


def evaluate_dft(fhat, L, p):
    n = len(L); f = [0]*n
    for i, x in enumerate(L):
        v = 0
        for j in range(len(fhat)):
            if fhat[j]: v = (v + fhat[j]*pow(x, j, p)) % p
        f[i] = v
    return f


def precompute_lagrange_pairs(L_arr, info_sets, p):
    n = len(L_arr); pairs = []
    for T_idx, T in enumerate(info_sets):
        i, j = int(T[0]), int(T[1])
        yi, yj = int(L_arr[i]), int(L_arr[j])
        denom_i = (yi - yj) % p; denom_j = (yj - yi) % p
        inv_di = modinv(denom_i, p); inv_dj = modinv(denom_j, p)
        T_set = {i, j}; kpairs = []
        for k in range(n):
            if k in T_set: continue
            yk = int(L_arr[k])
            c_ik = ((yk - yj) * inv_di) % p
            c_jk = ((yk - yi) * inv_dj) % p
            kpairs.append((k, c_ik, c_jk))
        pairs.append((T_idx, (i, j), kpairs))
    return pairs


def find_bad_alpha1(fold1_e_func, fold1_o_func, lagrange_pairs, p, n2, k2, w_J):
    """Given functions on L_2 (already split), find α_2's making it bad.
    Return: dict {alpha_2: count of always-bad info_sets} sort of thing.
    Actually return: True if for ALL α_2 the fold² is bad (= row saturating).
    """
    n_T = len(lagrange_pairs)
    extras_per_T = np.zeros((n_T, p), dtype=np.int64)
    fe = [int(x) for x in fold1_e_func]; fo = [int(x) for x in fold1_o_func]
    for T_idx, (i, j), kpairs in lagrange_pairs:
        always = 0; targets = []
        for k, c_ik, c_jk in kpairs:
            de = (c_ik * fe[i] + c_jk * fe[j] - fe[k]) % p
            do = (c_ik * fo[i] + c_jk * fo[j] - fo[k]) % p
            if do == 0:
                if de == 0: always += 1
            else:
                a2 = (-de * modinv(do, p)) % p
                targets.append(a2)
        if always: extras_per_T[T_idx, :] += always
        if targets:
            bc = np.bincount(np.array(targets, dtype=np.int64), minlength=p)
            extras_per_T[T_idx, :] += bc
    max_ex = extras_per_T.max(axis=0)
    d_vec = (n2 - k2 - max_ex)
    return (d_vec <= w_J).astype(np.int8)


def main():
    p = 97
    n0, k0 = 32, 8
    n1, k1 = 16, 4
    n2, k2 = 8, 2
    w_J_L2 = 4

    chain = setup_chain(p, n0, k0, R=2)
    L0 = chain[0][0]; L1 = chain[1][0]; L2 = chain[2][0]
    L2_arr = np.array(L2, dtype=np.int64)
    L1_arr = np.array(L1, dtype=np.int64)
    info_sets_n2 = np.array(list(combinations(range(n2), k2)), dtype=np.int64)
    lp = precompute_lagrange_pairs(L2_arr, info_sets_n2, p)

    print(f"=== Saturating α_1 structure: (15,18,19) at (32,8), q={p} ===")
    print(f"  L_0 = {L0[:6]}... (n={n0})")
    print(f"  L_1 = {L1[:6]}... (n={n1})")
    print(f"  L_2 = {L2}")
    print(f"  z^4 on L_2: {[pow(int(z), 4, p) for z in L2]}  (sign character)")
    print()

    # Compute multiplicative subgroup structure on L_2
    # L_2 is generated by ω^4. We want to know which subgroups of order 4, 2 sit inside.
    g = int(L2[1])  # generator
    print(f"  Generator of L_2 (order 8): g = {g}")
    print(f"  g^2 = {pow(g, 2, p)} (generates order-4 subgroup)")
    print(f"  g^4 = {pow(g, 4, p)} (= -1 mod p; sign generator)")
    print(f"  g^8 = {pow(g, 8, p)} (= 1)")
    print()

    sup = (15, 18, 19)
    for trial in range(3):
        random.seed(2026 + trial)
        coefs = [random.randrange(1, p-1) for _ in range(3)]
        fhat = [0]*n0
        for j, c in zip(sup, coefs): fhat[j] = c % p
        f = evaluate_dft(fhat, L0, p)
        f_e, f_o = even_odd_parts(f, L0, p)

        # Sweep α_1
        sat_a1 = []
        for a1 in range(p):
            fold1_arr = [(int(f_e[i]) + a1 * int(f_o[i])) % p for i in range(n1)]
            fold1_e, fold1_o = even_odd_parts(fold1_arr, L1, p)
            bad_vec = find_bad_alpha1(fold1_e, fold1_o, lp, p, n2, k2, w_J_L2)
            if int(bad_vec.sum()) == p:
                sat_a1.append(a1)

        # Also compute (f_e)_o, (f_o)_o on L_2 from the components
        fe_e, fe_o = even_odd_parts(f_e, L1, p)
        fo_e, fo_o = even_odd_parts(f_o, L1, p)
        # Note: (f_e)_o = "fe_o" on L_2 (odd part of f_e, restricted to L_2)
        # Wait — even_odd_parts(f_e, L1, p) gives the Fourier-split components
        # restricted to L_2 = halve(L_1). Confirm.

        print(f"--- Trial {trial}, coefs={coefs} ---")
        print(f"  Saturating α_1's ({len(sat_a1)}): {sat_a1}")
        if len(sat_a1) >= 2:
            # Test additive subgroup / coset
            diffs = sorted(set((b - sat_a1[0]) % p for b in sat_a1))
            print(f"  α_1 - α_1[0] (sorted): {diffs[:10]}")
            # Multiplicative ratios (treating as F_p^*)
            if 0 not in sat_a1:
                ratios = sorted(set(((b * modinv(sat_a1[0], p)) % p) for b in sat_a1))
                print(f"  α_1 / α_1[0]: {ratios[:10]}")
            else:
                print(f"  0 ∈ saturating set, ratios skipped")

        # Compute (f_e)_o, (f_o)_o on L_2 as actual functions
        print(f"  (f_e)_o on L_2: {[int(x) for x in fe_o]}")
        print(f"  (f_o)_o on L_2: {[int(x) for x in fo_o]}")

        # h(α_1) = (f_e)_o + α_1·(f_o)_o
        # Test which α_1 make h bad on L_2 = RS_2(L_2)
        # RS_2 means polynomial degree < 2, i.e., affine a_0 + a_1·z
        # h is bad iff agrees with affine on ≥ k_2 + (n_2 - w_J - k_2) = n_2 - w_J = 4 positions
        # i.e., dist(h, RS_2) ≤ w_J = 4
        # For 1-line pencil bad-α counting on L_2:
        bad_h = []
        for a1 in range(p):
            h = [(int(fe_o[i]) + a1 * int(fo_o[i])) % p for i in range(n2)]
            # Check if h ∈ Johnson ball of RS_2(L_2)
            min_dist = n2
            # Iterate over possible (a_0, a_1) — too expensive p^2 = 9409 for each α_1
            # Instead: pick best 2-info-set fit and compute distance
            for T in info_sets_n2:
                i, j = int(T[0]), int(T[1])
                yi, yj = int(L2_arr[i]), int(L2_arr[j])
                denom = (yi - yj) % p
                if denom == 0: continue
                a1_lin = ((h[i] - h[j]) * modinv(denom, p)) % p
                a0_lin = (h[i] - a1_lin * yi) % p
                # Compute distance to a_0 + a_1·z on L_2
                d = 0
                for ii in range(n2):
                    if (a0_lin + a1_lin * int(L2_arr[ii])) % p != h[ii]:
                        d += 1
                if d < min_dist: min_dist = d
                if min_dist <= w_J_L2: break
            if min_dist <= w_J_L2:
                bad_h.append(a1)
        print(f"  α_1 with h(α_1) bad on L_2 ({len(bad_h)}): {bad_h}")
        # If |bad_h| ≤ 9 and matches sat_a1, we've located the bottleneck
        print(f"  match sat_a1 == bad_h? {sorted(sat_a1) == sorted(bad_h)}")
        print()


if __name__ == "__main__":
    main()
