"""g3_y0y2_only.py — does y0 + y2 layer alone close Stage 2?

Stage 2 ideal generally = ideal generated by [z^c] [s^j] (αβ) = 0 for
c = 1..h-1, j = 0..4. (αβ has degree 4 in s besides the s⁸ - 1/16 term.)

I want to test: does the SUB-IDEAL {y0_c, y2_c}_c=1..h-1 alone close?
i.e., does its V already equal {0}, or do we need y1, y3, y4 too?
"""
from __future__ import annotations

import argparse
import time
import sympy as sp


def build_y0_y2_only(h):
    s, z = sp.symbols("s z")
    x = [sp.Symbol(f"x{i}") for i in range(1, h)]

    P0 = s**4 + s**3 - sp.Rational(1, 2) * s - sp.Rational(1, 4)
    R0 = s**4 - s**3 + s**2 - sp.Rational(1, 2) * s + sp.Rational(1, 4)
    X = sum(x[i - 1] * z**i for i in range(1, h))
    X2 = sp.expand(X * X)
    Wc = {c: X2.coeff(z, h + c) for c in range(1, h)}

    P = sum((sp.Rational(3, 2) * x[c - 1] - sp.Rational(1, 2) * Wc[c]
             + x[c - 1] * s) * z**c for c in range(1, h))
    R = sum((sp.Rational(1, 2) * x[c - 1] + sp.Rational(1, 2) * Wc[c]
             - x[c - 1] * s) * z**c for c in range(1, h))

    direct = sp.expand((P0 + P) * (R0 + R))

    poly_z = sp.Poly(direct, z)
    coefs = poly_z.all_coeffs()[::-1]
    in_A = sp.Integer(0)
    for d, c in enumerate(coefs):
        shift = d
        cc = c
        while shift >= h:
            shift -= h
            cc = cc * s
        in_A += cc * z**shift
    in_A = sp.expand(in_A)

    constraints_y0y2 = []
    constraints_all = []
    for c in range(1, h):
        coef_zc = sp.Poly(in_A, z).coeff_monomial(z**c)
        coef_zc_poly_s = sp.Poly(coef_zc, s)
        deg_s = coef_zc_poly_s.degree()
        for j in range(deg_s + 1):
            cc = coef_zc_poly_s.coeff_monomial(s**j)
            if cc != 0:
                constraints_all.append((c, j, sp.expand(cc)))
                if j in (0, 2):
                    constraints_y0y2.append(sp.expand(cc))
    return x, constraints_y0y2, constraints_all


def gb_close(constraints, x, label):
    t0 = time.time()
    G = sp.groebner(constraints, *x, order="grevlex")
    dt = time.time() - t0
    in_G = []
    for xi in x:
        # Check if xi reduces to 0 mod G.
        r = sp.reduced(xi, G)
        in_G.append((str(xi), r[1] == 0))
    closes = all(b for _, b in in_G)
    print(f"  [{label}] |G|={len(G)}, time={dt:.2f}s, closes={closes}")
    if not closes:
        not_in = [n for n, b in in_G if not b]
        print(f"    Vars not killed: {not_in}")
        # Show GB
        print(f"    GB: {[str(sp.factor(g))[:80] for g in G[:8]]}")
    return closes


def test_h(h):
    print(f"\n========== h = {h} ==========")
    x, c_y0y2, c_all = build_y0_y2_only(h)
    print(f"  y0+y2 layer: {len(c_y0y2)} constraints")
    print(f"  full Stage 2 (y0..y4): {len(c_all)} constraints")
    by_layer = {}
    for c, j, _ in c_all:
        by_layer[j] = by_layer.get(j, 0) + 1
    print(f"  layers breakdown: {sorted(by_layer.items())}")

    c_y0_only = [p for c, j, p in c_all if j == 0]
    c_y2_only = [p for c, j, p in c_all if j == 2]
    c_y1_only = [p for c, j, p in c_all if j == 1]
    closes_y0 = gb_close(c_y0_only, x, "y0 only")
    closes_y2 = gb_close(c_y2_only, x, "y2 only")
    closes_y1 = gb_close(c_y1_only, x, "y1 only")
    closes_y0y2 = gb_close(c_y0y2, x, "y0+y2")
    closes_all = gb_close([p for _, _, p in c_all], x, "full Stage 2 (y0+y1+y2)")
    return closes_y0, closes_y2, closes_y1, closes_y0y2, closes_all


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--h-list", default="3,4,5,6,7")
    args = parser.parse_args()
    for h in args.h_list.split(","):
        test_h(int(h))


if __name__ == "__main__":
    main()
